use crate::items::{Bosses, Vouchers, Tags, Tarots, Planets};

pub fn boss_name(b: &Bosses) -> &'static str {
    match b {
        Bosses::TheArm => "The Arm",
        Bosses::TheClub => "The Club",
        Bosses::TheEye => "The Eye",
        Bosses::AmberAcorn => "Amber Acorn",
        Bosses::CeruleanBell => "Cerulean Bell",
        Bosses::CrimsonHeart => "Crimson Heart",
        Bosses::VerdantLeaf => "Verdant Leaf",
        Bosses::VioletVessel => "Violet Vessel",
        Bosses::TheFish => "The Fish",
        Bosses::TheFlint => "The Flint",
        Bosses::TheGoad => "The Goad",
        Bosses::TheHead => "The Head",
        Bosses::TheHook => "The Hook",
        Bosses::TheHouse => "The House",
        Bosses::TheManacle => "The Manacle",
        Bosses::TheMark => "The Mark",
        Bosses::TheMouth => "The Mouth",
        Bosses::TheNeedle => "The Needle",
        Bosses::TheOx => "The Ox",
        Bosses::ThePillar => "The Pillar",
        Bosses::ThePlant => "The Plant",
        Bosses::ThePsychic => "The Psychic",
        Bosses::TheSerpent => "The Serpent",
        Bosses::TheTooth => "The Tooth",
        Bosses::TheWall => "The Wall",
        Bosses::TheWater => "The Water",
        Bosses::TheWheel => "The Wheel",
        Bosses::TheWindow => "The Window",
    }
}

pub fn tag_name(t: &Tags) -> &'static str {
    match t {
        Tags::UncommonTag => "Uncommon Tag",
        Tags::RareTag => "Rare Tag",
        Tags::NegativeTag => "Negative Tag",
        Tags::FoilTag => "Foil Tag",
        Tags::HolographicTag => "Holographic Tag",
        Tags::PolychromeTag => "Polychrome Tag",
        Tags::InvestmentTag => "Investment Tag",
        Tags::VoucherTag => "Voucher Tag",
        Tags::BossTag => "Boss Tag",
        Tags::StandardTag => "Standard Tag",
        Tags::CharmTag => "Charm Tag",
        Tags::MeteorTag => "Meteor Tag",
        Tags::BuffoonTag => "Buffoon Tag",
        Tags::HandyTag => "Handy Tag",
        Tags::GarbageTag => "Garbage Tag",
        Tags::EtherealTag => "Ethereal Tag",
        Tags::CouponTag => "Coupon Tag",
        Tags::DoubleTag => "Double Tag",
        Tags::JuggleTag => "Juggle Tag",
        Tags::D6Tag => "D6 Tag",
        Tags::TopUpTag => "Top-up Tag",
        Tags::SpeedTag => "Speed Tag",
        Tags::OrbitalTag => "Orbital Tag",
        Tags::EconomyTag => "Economy Tag",
    }
}

pub fn tarot_name(t: &Tarots) -> &'static str {
    match t {
        Tarots::TheFool => "The Fool",
        Tarots::TheMagician => "The Magician",
        Tarots::TheHighPriestess => "The High Priestess",
        Tarots::TheEmpress => "The Empress",
        Tarots::TheEmperor => "The Emperor",
        Tarots::TheHierophant => "The Hierophant",
        Tarots::TheLovers => "The Lovers",
        Tarots::TheChariot => "The Chariot",
        Tarots::Justice => "Justice",
        Tarots::TheHermit => "The Hermit",
        Tarots::TheWheelOfFortune => "The Wheel of Fortune",
        Tarots::Strength => "Strength",
        Tarots::TheHangedMan => "The Hanged Man",
        Tarots::Death => "Death",
        Tarots::Temperance => "Temperance",
        Tarots::TheDevil => "The Devil",
        Tarots::TheTower => "The Tower",
        Tarots::TheStar => "The Star",
        Tarots::TheMoon => "The Moon",
        Tarots::TheSun => "The Sun",
        Tarots::Judgement => "Judgement",
        Tarots::TheWorld => "The World",
    }
}

pub fn planet_name(p: &Planets) -> &'static str {
    match p {
        Planets::Mercury => "Mercury",
        Planets::Venus => "Venus",
        Planets::Earth => "Earth",
        Planets::Mars => "Mars",
        Planets::Jupiter => "Jupiter",
        Planets::Saturn => "Saturn",
        Planets::Uranus => "Uranus",
        Planets::Neptune => "Neptune",
        Planets::Pluto => "Pluto",
        Planets::PlanetX => "Planet X",
        Planets::Ceres => "Ceres",
        Planets::Eris => "Eris",
    }
}

pub fn voucher_name(v: &Vouchers) -> &'static str {
    match v {
        Vouchers::Overstock => "Overstock",
        Vouchers::OverstockPlus => "Overstock Plus",
        Vouchers::ClearanceSale => "Clearance Sale",
        Vouchers::Liquidation => "Liquidation",
        Vouchers::Hone => "Hone",
        Vouchers::GlowUp => "Glow Up",
        Vouchers::RerollSurplus => "Reroll Surplus",
        Vouchers::RerollGlut => "Reroll Glut",
        Vouchers::CrystalBall => "Crystal Ball",
        Vouchers::OmenGlobe => "Omen Globe",
        Vouchers::Telescope => "Telescope",
        Vouchers::Observatory => "Observatory",
        Vouchers::Grabber => "Grabber",
        Vouchers::NachoTong => "Nacho Tong",
        Vouchers::Wasteful => "Wasteful",
        Vouchers::Recyclomancy => "Recyclomancy",
        Vouchers::TarotMerchant => "Tarot Merchant",
        Vouchers::TarotTycoon => "Tarot Tycoon",
        Vouchers::PlanetMerchant => "Planet Merchant",
        Vouchers::PlanetTycoon => "Planet Tycoon",
        Vouchers::SeedMoney => "Seed Money",
        Vouchers::MoneyTree => "Money Tree",
        Vouchers::Blank => "Blank",
        Vouchers::Antimatter => "Antimatter",
        Vouchers::MagicTrick => "Magic Trick",
        Vouchers::Illusion => "Illusion",
        Vouchers::Hieroglyph => "Hieroglyph",
        Vouchers::Petroglyph => "Petroglyph",
        Vouchers::DirectorsCut => "Director's Cut",
        Vouchers::Retcon => "Retcon",
        Vouchers::PaintBrush => "Paint Brush",
        Vouchers::Palette => "Palette",
    }
}
